server:
  port: 3333

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/finance-app-database?schema=finance-app
    username: postgres
    password: postgres

  liquibase:
    default-schema: finance-app
