server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/finance-app-database?schema=finance_app
    username: postgres
    password: postgres
  security:
    oauth2:
      client:
        registration:
          finance-app-oidc:
            provider: spring
            client-id: finance-app
            client-secret: secret
            client-name: finance-app-oidc
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
          finance-app-authorization-code:
            provider: spring
            client-id: finance-app
            client-secret: secret
            client-name: finance-app-authorization-code
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
        provider:
          spring:
            issuer-uri: http://auth-server:9000
  liquibase:
    default-schema: finance_app
