server:
  port: 3333

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/finance-app-database?schema=finance_app
    username: postgres
    password: postgres

liquibase:
  default-schema: finance_app
