server:
  port: ${PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      schema: finance_app

liquibase:
  contexts: local
  enabled: false