version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

  keycloak-compose:
    image: quay.io/keycloak/keycloak:18.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB_URL_HOST=postgres-compose
      - KC_DB_URL_PORT=5432
      - KC_DB_SCHEMA=sso_server
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

#  finance-app-compose:
#    image: finance-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - DATABASE_URL=postgres-compose/finance-app-database?schema=finance_app
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - ISSUER_URI=keycloak-compose:8080
#      - ISSUER_REALM=finance-app
#    ports:
#      - "8082:8080"
#    depends_on:
#      - postgres-compose
#      - keycloak-compose
#    networks:
#      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
