FROM openjdk:18
COPY ./target/*.jar /app.jar

ENV PORT=$PORT
ENV DATABASE_URL=$DATABASE_URL
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV ISSUER_URI=$ISSUER_URI
ENV ISSUER_REALM=$ISSUER_HOST

ENTRYPOINT ["java", "-jar", "/app.jar"]
EXPOSE $PORT
