server:
  port: ${PORT}

logging:
  level:
    root: INFO

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${SCHEMA}
      connectionTimeout: 20000
      maximum-pool-size: 5

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}

  liquibase:
    default-schema: ${SCHEMA}
    enabled: true

  cloud:
    openfeign:
      client:
        config:
          CURRENCY:
            url: https://economia.awesomeapi.com.br/json/last

