server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  datasource:
    url: url
    username: username
    password: password
    hikari:
      schema: schema
      connectionTimeout: 20000
      maximum-pool-size: 5

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: issuer-uri
          jwk-set-uri: jwk-set

  liquibase:
    default-schema: schema
    enabled: true

