server:
  port: ${PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      schema: finance_app
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://${ISSUER_URI}/realms/${ISSUER_REALM}/protocol/openid-connect/certs

  liquibase:
    default-schema: finance_app
    contexts: local
    enabled: true
