# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build - finance-app-backend-java

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Set up Java version
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '17'

      #TODO fix tests
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.3.3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'