name: Trigger auto deployment for finance-app-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/finance-app-backend-AutoDeployTrigger-d8838f15-8343-4a61-b376-49464c1a7d6e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.FINANCEAPPBACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.FINANCEAPPBACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: viictrp/finance-app-backend:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FINANCEAPPBACKEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n finance-app-backend -g financea-pp --server docker.io --username  ${{ secrets.FINANCEAPPBACKEND_REGISTRY_USERNAME }} --password ${{ secrets.FINANCEAPPBACKEND_REGISTRY_PASSWORD }}
            az containerapp update -n finance-app-backend -g financea-pp --image viictrp/finance-app-backend:${{ github.sha }}
